apiVersion: v1
kind: Service
metadata:
  name: ocrapp-elsondevops-svc
  labels:
    app: ocrapp-elsondevops
spec:
  type: ClusterIP
  selector:
    app: ocrapp-elsondevops
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
